---
version: '2'
services:
  app:
    image: phoenix:1.3.3
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./src:/app
    depends_on:
      - db
  #   links:
  #     - rethinkdb:localhost
  db:
    image: postgres:9.4
    volumes:
      - ./postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: leather
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: leather_dev
  # rethinkdb:
  #   image: rethinkdb
  #   volumes:
  #     - ".:/data"
  #   ports:
  #     - "8080:8080"